version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/application"
    target-branch: main
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    labels:
      - "npm"
      - "dependencies"
      - "no-action"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "no-action"