name: Deploy app to EKS
on:
  workflow_call:
    inputs:
      deployment_name: 
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      image_repository:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      working_directory:
        required: false
        type: string
        default: application/helmchart
      environment:
        required: false
        type: string
        default: staging
      service_type:
        required: false
        type: string
        default: LoadBalancer
      namespace:
        required: false
        type: string
        default: development

jobs:
  deploy:
    name: Deploy app to EKS
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Update kubeconfig file with EKS
      run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION || 'us-east-1' }} --name ${{ secrets.CLUSTER_NAME }}

    - name: Deploy helm chart
      run: |
        helm upgrade --install "${{ inputs.deployment_name }}" . \
        --namespace "${{ inputs.namespace }}" \
        --create-namespace \
        --set image.repository="${{ inputs.image_repository }}" \
        --set image.tag="${{ inputs.image_tag }}" \
        --set configMap.data.environment="${{ inputs.environment }}" \
        --set service.type="${{ inputs.service_type }}" \
        --set secret.data.database_name="${{ secrets.DATABASE_NAME }}" \
        --set secret.data.database_user="${{ secrets.DATABASE_USER }}" \
        --set secret.data.database_password="${{ secrets.DATABASE_PASSWORD }}"
        --set ingress.enabled=true


    # - name: Install Karpenter
    #   uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION }}
    #     cluster-name: ${{ secrets.CLUSTER_NAME }}
    #     helm-wait: true
    #     namespace: ${{ inputs.namespace }}
    #     name: ${{ inputs.deployment_name }}
    #     values: |
    #       settings.clusterName=${{ vars.CLUSTER_NAME }},
    #       settings.interruptionQueue=${{ vars.CLUSTER_NAME }}-karpenter,
    #       controller.resources.requests.cpu=1,
    #       controller.resources.requests.memory=1Gi,
    #       controller.resources.limits.cpu=1,
    #       controller.resources.limits.memory=1Gi