name: Deploy development enviroment
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
      - application/**/*
      - "**/*.js"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - ".github/workflows/development.yml"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/clean.yml"
    types: [opened, synchronize, reopened, labeled]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  test:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-action') }}
    name: 'Test project'
    runs-on: ubuntu-24.04
    environment: development
    defaults:
      run:
        working-directory: application
    outputs:
      short_sha: ${{ steps.shorten_sha.outputs.short_sha }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean install modules
      run: npm ci
    
    - name: Unit Testing and Code Coverage
      run: |-
        npm i jest
        npm run coverage

    - name: Shorten commit SHA
      id: shorten_sha
      run: |
        SHORTEN_SHA=$(echo "${{ github.head_ref }}" | sha256sum | cut -c 1-5)
        echo "short_sha=$SHORTEN_SHA" >> $GITHUB_OUTPUT

  build-and-push:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-action') }}
    needs:
    - test
    uses: ./.github/workflows/build.yaml
    with:
      working_directory: application/
      environment: development
      image_tag: devsu-test-nodejs-${{ needs.test.outputs.short_sha }}
    secrets: inherit
    

  deploy:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-action') }}
    needs:
    - test
    - build-and-push
    uses: ./.github/workflows/deploy.yaml
    with:
      working_directory: application/helmchart
      environment: development
      image_tag: ${{ needs.build-and-push.outputs.ecr_image_tag }}
      image_repository: ${{ needs.build-and-push.outputs.ecr_image_repository }}
      deployment_name: devsu-test-nodejs-${{ needs.test.outputs.short_sha }}
      service_type: LoadBalancer
      namespace: development-${{ needs.test.outputs.short_sha }}
    secrets: inherit
    

    

