name: Deploy development enviroment
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
      - application/**/*
      - "**/*.js"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - ".github/workflows/development.yml"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/clean.yml"
    types: [opened, synchronize, reopened, labeled]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  test:
    name: 'Test project'
    runs-on: ubuntu-24.04
    environment: development
    defaults:
      run:
        working-directory: application
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean install modules
      run: npm ci
    
    - name: Unit Testing and Code Coverage
      run: |-
        npm i jest
        npm run coverage

  build-and-push:
    needs:
    - test
    uses: ./.github/workflows/build.yaml
    with:
      working_directory: application/
      environment: development
      image_name: devsu-test-nodejs
    secrets: inherit

  deploy:
    needs:
    - test
    - build-and-push
    uses: ./.github/workflows/deploy.yaml
    with:
      working_directory: application/helmchart
      environment: development
      image_tag: ${{ needs.build-and-push.ouputs.image_tag }}
      image_repository: ${{ needs.build-and-push.ouputs.image_repository }}
      deployment_name: devsu-test-nodejs-$(git rev-parse --short ${{ github.sha }})
      service_type: LoadBalancer
      namespace: development-$(git rev-parse --short ${{ github.sha }})
    secrets: inherit
    

    

