name: Deploy development enviroment
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
      - application/**/*
      - "**/*.js"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - ".github/workflows/development.yml"
      - ".github/workflows/clean.yml"
    types: [opened, synchronize, reopened, labeled]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  test:
    name: 'Test project'
    runs-on: ubuntu-24.04
    environment: development
    defaults:
      run:
        working-directory: application
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Audit and fix npm Packages
      run: |
        echo "Running npm audit..."
        npm audit || true
        echo "Attempting to fix vulnerabilities..."
        npm audit fix || true
        echo "Rechecking vulnerabilities after fix..."
        npm audit || true
      continue-on-error: true
    
    - name: Unit Testing and Code Coverage
      run: |-
        npm i jest
        npm run coverage

  build-and-push:
    needs:
    - test
    uses: ./.github/workflows/build.yaml
    with:
      working_directory: application
      environment: development
      image_name: devsu-test-nodejs
    secrets: inherit
    

    

