name: Deploy release/production enviroment
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  test:
    name: 'Test project'
    runs-on: ubuntu-24.04
    environment: production
    defaults:
      run:
        working-directory: application
    outputs:
      image_tag: ${{ steps.image_info.outputs.image_tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean install modules
      run: npm ci
    
    - name: Unit Testing and Code Coverage
      run: |-
        npm i jest
        npm run coverage

    - name: Setting image info
      id: image_info
      run: |
        echo "image_tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT


  build-and-push:
    needs:
    - test
    uses: ./.github/workflows/build.yaml
    with:
      working_directory: application/
      environment: production
      image_tag: ${{ needs.test.outputs.image_tag }}
    secrets: inherit
    
  deploy:
    needs:
    - test
    - build-and-push
    uses: ./.github/workflows/deploy.yaml
    with:
      working_directory: application/helmchart
      environment: production
      image_tag: ${{ needs.test.outputs.image_tag }}
      deployment_name: devsu-test-nodejs-production
      service_type: NodePort
      namespace: devsu-test-nodejs-production
    secrets: inherit
    

    

