name: Deploy staging enviroment
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
      - application/**/*
      - "**/*.js"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - ".github/workflows/development.yaml"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/build.yaml"
      - ".github/workflows/clean.yaml"
      - ".github/workflows/staging.yaml"
    types: [closed]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  test:
    name: 'Test project'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    environment: staging
    defaults:
      run:
        working-directory: application
    outputs:
      image_tag: ${{ steps.image_info.outputs.image_tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Clean install modules
      run: npm ci
    
    - name: Unit Testing and Code Coverage
      run: |-
        npm run test
        npm run coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Setting image info
      id: image_info
      run: |
        echo "image_tag=latest" >> $GITHUB_OUTPUT


  build-and-push:
    if: github.event.pull_request.merged == true
    needs:
    - test
    uses: ./.github/workflows/build.yaml
    with:
      working_directory: application/
      environment: staging
      image_tag: ${{ needs.test.outputs.image_tag }}
    secrets: inherit
    

  deploy:
    if: github.event.pull_request.merged == true
    needs:
    - test
    - build-and-push
    uses: ./.github/workflows/deploy.yaml
    with:
      working_directory: application/helmchart
      environment: staging
      image_tag: ${{ needs.test.outputs.image_tag }}
      deployment_name: devsu-test-nodejs-staging
      service_type: NodePort
      namespace: devsu-test-nodejs-staging
    secrets: inherit

  post-deploy:
    if: github.event.pull_request.merged == true
    needs:
    - test
    - build-and-push
    - deploy
    uses: ./.github/workflows/post-deploy.yaml
    with:
      environment: staging
      deployment_name: devsu-test-nodejs-staging
    secrets: inherit
    

    

